name: New Relic Deployment

on:
  push:
    branches:
      - main  # Replace with the branch you want to trigger deployments from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Add your build and deployment steps here
      # For example:
      # - name: Build and Deploy
      #   run: |
      #     npm install
      #     npm build
      #     # Your deployment command here
      
      - name: Deploy to New Relic
        run: |
         # Replace the placeholders with actual values
         APPLICATION_NAME="testphp/index.php"
         REVISION="6bb1f7948150b8b211bbcf0fa4d69d963550ae97"
         NEWRELIC_API_KEY="366e2eec8072a7956ebe462c559ebf89FFFFNRAL"
    
         newrelic deployments \
          --appname="$APPLICATION_NAME" \
          --revision="$REVISION" \
          --user="$GITHUB_ACTOR" \
          --description="Deployment from GitHub Actions" \
          --apikey="$NEWRELIC_API_KEY"
      - name: Notify New Relic
        run: |
          curl -X POST "https://api.newrelic.com/v2/applications/581682573/deployments.json" \
          -H "X-Api-Key: 366e2eec8072a7956ebe462c559ebf89FFFFNRAL" \
          -d "deployment[revision]=${GITHUB_SHA:0:7}" \
          -d "deployment[user]=${GITHUB_ACTOR}" \
          -d "deployment[changelog]=${{ github.event.head_commit.message }}"

